steps:
- name: gcr.io/cloud-builders/gcloud
  id: Build Docker Image
  args: ['builds', 'submit', '--tag', 'gcr.io/${_PROJECT_ID}/${_IMAGE_NAME}:${_IMAGE_TAG}', '.']
  waitFor: ['-']
- name: gcr.io/cloud-builders/gcloud
  args: ['beta',
         'dataflow',
         'flex-template',
         'build',
         'gs://${_BUCKET_NAME}/dataflow_templates/bq_to_csv_template.json',
         '--image=gcr.io/${_PROJECT_ID}/${_IMAGE_NAME}:${_IMAGE_TAG}',
         '--sdk-language=PYTHON',
         '--metadata-file=pipeline_metadata.json'
  ]
  waitFor: ['Build Docker Image']

substitutions:
  _BUCKET_NAME: 'YOUR BUCKET NAME'
  _PROJECT_ID: 'YOUR PROJECT ID'
  _IMAGE_NAME: 'YOUR IMAGE NAME'
  _IMAGE_TAG: 'YOUR TAG NAME'
